namespace RTMLIS;

internal enum ASTM_STATE
{
	ASTM_READ_IDLE,
	ASTM_READ_WAITING_FOR_STX,
	ASTM_READ_WAITING_FOR_FN,
	ASTM_READ_WAITING_FOR_ETB_OR_ETX,
	ASTM_READ_WAITING_FOR_CHECKSUM_MSB,
	ASTM_READ_WAITING_FOR_CHECKSUM_LSB,
	ASTM_READ_WAITING_FOR_CR,
	ASTM_READ_WAITING_FOR_LF,
	ASTM_WRITE_STATE,
	ASTM_WRITE_WAITING_TO_SEND,
	ASTM_WRITE_SEND_PACKET,
	ASTM_WRITE_WAITING_FOR_SEND_ACK
}
