server:
  port: 9005
  servlet:
    context-path: /anno

spring:
  profiles:
    active: dev
  application:
    name: jnet-anno
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
