
spring:
  jackson:
    # 序列化配置
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    # 反序列化配置
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
    # 日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    enabled: false
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: 192.168.52.108:8848
      discovery:
        auto-registration: true
        server-addr: 192.168.52.108:8848
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # 生产环境建议使用 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        spatial:
          enabled: true
        type:
          descriptor:
            sql:
              SqlTypes:
                GEOMETRY: org.hibernate.type.descriptor.sql.GeometrySqlDescriptor
    open-in-view: false  # 性能优化
  data:
    redis:
      #Redis 连接的超时时间
      timeout: 5000
      #Redis 索引（0~15，默认为0）
      database: 10
      host: 192.168.160.103
      port: 6379
      password: shengtong
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/jnet
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 5000
      validation-timeout: 5000
      auto-commit: true
      pool-name: "HikariCP"
      connection-test-query: "SELECT 1"
      register-mbeans: true
  thymeleaf:
    check-template-location: false
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
#prometheus配置
info:
  alen: alen
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.jnet.anno.controller,com.jnet.anno.vo.*
  default-flat-param-object: true
netty:
  port: 7777


