using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Builders;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Yzkj.Novanet.Data.Migrations;

[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
public sealed class _20170627_update_setupGroup : DbMigration, IMigrationMetadata
{
	private readonly ResourceManager Resources = new ResourceManager(typeof(_20170627_update_setupGroup));

	string IMigrationMetadata.Id => "201706260721309_20170627_update_setupGroup";

	string IMigrationMetadata.Source => null;

	string IMigrationMetadata.Target => Resources.GetString("Target");

	public override void Up()
	{
		DropForeignKey("dbo.NovaSetupGroups", "novaSetupId", "dbo.NovaSetups");
		DropIndex("dbo.NovaSetupGroups", new string[1] { "novaSetupId" });
		AddColumn("dbo.NovaSetupGroups", "AccnId2DsEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdAlphaEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanEnable2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanEnableCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdSm2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdSmC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdSmC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdSmC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdSmC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdSmCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxId2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdAlphaEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdPromptEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanEnable2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanEnableC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanEnableC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanEnableC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanEnableC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanEnableCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdSm2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdSmC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdSmC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdSmC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdSmC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdSmCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ArchivedObsRetainDays", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ArchivedOvrwDisregardArchBit", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DockLockAlertMins", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DockLockElapsedHrs", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DockLockInterval", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DockLockModeCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DockLockShiftTimes", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DockLockSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdMaxLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdMinLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdMaxLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DxIdMinLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginMaxLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginMinLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdMaxLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdMinLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdMaxLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdMinLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinLot2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinLotListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinLotNonBarcodeCmntReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinLotScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinLotScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinLotSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinLotValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdTypeCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLogoffElapsedSecs", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLogoffModeCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "DateFormat", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "MeterMaxLinRec", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "MeterMaxPatRec", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "MeterMaxProfRec", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "MeterMaxQCRec", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "TimeFormat", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLogin2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginAlphaEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginDisplayCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanEnable2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanEnableCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginSm2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginSmC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginSmC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginSmC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginSmC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginSmCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "OpLoginValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "SupOverrideSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "SupOvScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "SupOvScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatId2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdAlphaEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdAutoEnabled", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdFailCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdFailDowntimeEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdFailNewPtEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanEnable2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanEnableC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanEnableC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanEnableC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanEnableC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanEnableCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdSm2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdSmC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdSmC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdSmC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdSmC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdSmCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdTgcEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "CommentsFreeTextChartableEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "CommentsFreeTextEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "CommentsFreeTextFlaggedEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinObsFailCommentReqCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinObsPassCommentReqCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "LinObsValueDisplay", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsAbnormalRangeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsCriticalRangeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsNormalRangeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsRejectEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsRejectResultCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsRejectSupOverrideReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsReviewNoLogin", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsTechnicalRangeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcObsFailCommentReqCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcObsPassCommentReqCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcObsValueDisplay", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysId2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdAlphaEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdPromptEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanEnable2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanEnableCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdSm2D", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdSmC128", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdSmC2o5", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdSmC39", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdSmC93", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdSmCbar", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PhysIdValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelAdminRenameMeterCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelAdminResetFacilityCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelAdminSetNetworkCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelAdminUnarchiveBitCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelDockLockOvCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelSetDateTimeCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeCorrelationCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeLinearityCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeMaintCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeProficiencyCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeTrainingCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLot2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotAlphaEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotMaxLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotMinLength", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfLotValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ProfRejectEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockAlertMins", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockElapsedHrs", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockInterval", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetAlertMins", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetElapsedHrs", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetInterval", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetLevel1Req", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetLevel2Req", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetLevel3Req", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetModeCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockKetShiftTimes", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockLevel1Req", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockLevel2Req", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockLevel3Req", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockLevel4Req", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockModeCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLockShiftTimes", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLot2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLotListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLotNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLotScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLotScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLotSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "QcLotValidation", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "AccnIdPromptText", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "ObsIdMethodCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "PatIdPromptText", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "SampleTypeSelectEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripId2dSEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdAutoEnabled", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdDefaultLastStripId", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdListEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdNonBarcodeCommentReq", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdScanEnableCd", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdScanRequireAccept", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdSupOverrideEnable", (ColumnBuilder c) => c.String());
		AddColumn("dbo.NovaSetupGroups", "StripIdValidation", (ColumnBuilder c) => c.String());
		DropColumn("dbo.NovaSetupGroups", "novaSetupId");
	}

	public override void Down()
	{
		AddColumn("dbo.NovaSetupGroups", "novaSetupId", (ColumnBuilder c) => c.Int(false));
		DropColumn("dbo.NovaSetupGroups", "StripIdValidation");
		DropColumn("dbo.NovaSetupGroups", "StripIdSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "StripIdScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "StripIdScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "StripIdNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "StripIdListEnable");
		DropColumn("dbo.NovaSetupGroups", "StripIdDefaultLastStripId");
		DropColumn("dbo.NovaSetupGroups", "StripIdAutoEnabled");
		DropColumn("dbo.NovaSetupGroups", "StripId2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "SampleTypeSelectEnable");
		DropColumn("dbo.NovaSetupGroups", "PatIdPromptText");
		DropColumn("dbo.NovaSetupGroups", "ObsIdMethodCd");
		DropColumn("dbo.NovaSetupGroups", "AccnIdPromptText");
		DropColumn("dbo.NovaSetupGroups", "QcLotValidation");
		DropColumn("dbo.NovaSetupGroups", "QcLotSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "QcLotScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "QcLotScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "QcLotNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "QcLotListEnable");
		DropColumn("dbo.NovaSetupGroups", "QcLot2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "QcLockShiftTimes");
		DropColumn("dbo.NovaSetupGroups", "QcLockModeCd");
		DropColumn("dbo.NovaSetupGroups", "QcLockLevel4Req");
		DropColumn("dbo.NovaSetupGroups", "QcLockLevel3Req");
		DropColumn("dbo.NovaSetupGroups", "QcLockLevel2Req");
		DropColumn("dbo.NovaSetupGroups", "QcLockLevel1Req");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetShiftTimes");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetModeCd");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetLevel3Req");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetLevel2Req");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetLevel1Req");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetInterval");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetElapsedHrs");
		DropColumn("dbo.NovaSetupGroups", "QcLockKetAlertMins");
		DropColumn("dbo.NovaSetupGroups", "QcLockInterval");
		DropColumn("dbo.NovaSetupGroups", "QcLockElapsedHrs");
		DropColumn("dbo.NovaSetupGroups", "QcLockAlertMins");
		DropColumn("dbo.NovaSetupGroups", "ProfRejectEnable");
		DropColumn("dbo.NovaSetupGroups", "ProfLotValidation");
		DropColumn("dbo.NovaSetupGroups", "ProfLotSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "ProfLotScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "ProfLotScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "ProfLotNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "ProfLotMinLength");
		DropColumn("dbo.NovaSetupGroups", "ProfLotMaxLength");
		DropColumn("dbo.NovaSetupGroups", "ProfLotListEnable");
		DropColumn("dbo.NovaSetupGroups", "ProfLotAlphaEnable");
		DropColumn("dbo.NovaSetupGroups", "ProfLot2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeTrainingCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeProficiencyCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeMaintCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeLinearityCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelTesttypeCorrelationCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelSetDateTimeCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelDockLockOvCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelAdminUnarchiveBitCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelAdminSetNetworkCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelAdminResetFacilityCd");
		DropColumn("dbo.NovaSetupGroups", "PrivLevelAdminRenameMeterCd");
		DropColumn("dbo.NovaSetupGroups", "PhysIdValidation");
		DropColumn("dbo.NovaSetupGroups", "PhysIdSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "PhysIdSmCbar");
		DropColumn("dbo.NovaSetupGroups", "PhysIdSmC93");
		DropColumn("dbo.NovaSetupGroups", "PhysIdSmC39");
		DropColumn("dbo.NovaSetupGroups", "PhysIdSmC2o5");
		DropColumn("dbo.NovaSetupGroups", "PhysIdSmC128");
		DropColumn("dbo.NovaSetupGroups", "PhysIdSm2D");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejCbar");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC93");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC39");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC2o5");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanMaskFailRejC128");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanEnableCbar");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC93");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC39");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC2o5");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanEnableC128");
		DropColumn("dbo.NovaSetupGroups", "PhysIdScanEnable2D");
		DropColumn("dbo.NovaSetupGroups", "PhysIdPromptEnable");
		DropColumn("dbo.NovaSetupGroups", "PhysIdNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "PhysIdListEnable");
		DropColumn("dbo.NovaSetupGroups", "PhysIdAlphaEnable");
		DropColumn("dbo.NovaSetupGroups", "PhysId2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "QcObsValueDisplay");
		DropColumn("dbo.NovaSetupGroups", "QcObsPassCommentReqCd");
		DropColumn("dbo.NovaSetupGroups", "QcObsFailCommentReqCd");
		DropColumn("dbo.NovaSetupGroups", "ObsTechnicalRangeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "ObsReviewNoLogin");
		DropColumn("dbo.NovaSetupGroups", "ObsRejectSupOverrideReq");
		DropColumn("dbo.NovaSetupGroups", "ObsRejectResultCommentReq");
		DropColumn("dbo.NovaSetupGroups", "ObsRejectEnable");
		DropColumn("dbo.NovaSetupGroups", "ObsNormalRangeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "ObsCriticalRangeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "ObsAbnormalRangeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "LinObsValueDisplay");
		DropColumn("dbo.NovaSetupGroups", "LinObsPassCommentReqCd");
		DropColumn("dbo.NovaSetupGroups", "LinObsFailCommentReqCd");
		DropColumn("dbo.NovaSetupGroups", "CommentsFreeTextFlaggedEnable");
		DropColumn("dbo.NovaSetupGroups", "CommentsFreeTextEnable");
		DropColumn("dbo.NovaSetupGroups", "CommentsFreeTextChartableEnable");
		DropColumn("dbo.NovaSetupGroups", "PatIdValidation");
		DropColumn("dbo.NovaSetupGroups", "PatIdTgcEnable");
		DropColumn("dbo.NovaSetupGroups", "PatIdSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "PatIdSmCbar");
		DropColumn("dbo.NovaSetupGroups", "PatIdSmC93");
		DropColumn("dbo.NovaSetupGroups", "PatIdSmC39");
		DropColumn("dbo.NovaSetupGroups", "PatIdSmC2o5");
		DropColumn("dbo.NovaSetupGroups", "PatIdSmC128");
		DropColumn("dbo.NovaSetupGroups", "PatIdSm2D");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejCbar");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC93");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC39");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC2o5");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanMaskFailRejC128");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanEnableCbar");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanEnableC93");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanEnableC39");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanEnableC2o5");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanEnableC128");
		DropColumn("dbo.NovaSetupGroups", "PatIdScanEnable2D");
		DropColumn("dbo.NovaSetupGroups", "PatIdNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "PatIdListEnable");
		DropColumn("dbo.NovaSetupGroups", "PatIdFailNewPtEnable");
		DropColumn("dbo.NovaSetupGroups", "PatIdFailDowntimeEnable");
		DropColumn("dbo.NovaSetupGroups", "PatIdFailCommentReq");
		DropColumn("dbo.NovaSetupGroups", "PatIdAutoEnabled");
		DropColumn("dbo.NovaSetupGroups", "PatIdAlphaEnable");
		DropColumn("dbo.NovaSetupGroups", "PatId2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "SupOvScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "SupOvScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "SupOverrideSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "OpLoginValidation");
		DropColumn("dbo.NovaSetupGroups", "OpLoginSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "OpLoginSmCbar");
		DropColumn("dbo.NovaSetupGroups", "OpLoginSmC93");
		DropColumn("dbo.NovaSetupGroups", "OpLoginSmC39");
		DropColumn("dbo.NovaSetupGroups", "OpLoginSmC2o5");
		DropColumn("dbo.NovaSetupGroups", "OpLoginSmC128");
		DropColumn("dbo.NovaSetupGroups", "OpLoginSm2D");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejCbar");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC93");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC39");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC2o5");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanMaskFailRejC128");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanEnableCbar");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC93");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC39");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC2o5");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanEnableC128");
		DropColumn("dbo.NovaSetupGroups", "OpLoginScanEnable2D");
		DropColumn("dbo.NovaSetupGroups", "OpLoginNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "OpLoginDisplayCd");
		DropColumn("dbo.NovaSetupGroups", "OpLoginAlphaEnable");
		DropColumn("dbo.NovaSetupGroups", "OpLogin2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "TimeFormat");
		DropColumn("dbo.NovaSetupGroups", "MeterMaxQCRec");
		DropColumn("dbo.NovaSetupGroups", "MeterMaxProfRec");
		DropColumn("dbo.NovaSetupGroups", "MeterMaxPatRec");
		DropColumn("dbo.NovaSetupGroups", "MeterMaxLinRec");
		DropColumn("dbo.NovaSetupGroups", "DateFormat");
		DropColumn("dbo.NovaSetupGroups", "OpLogoffModeCd");
		DropColumn("dbo.NovaSetupGroups", "OpLogoffElapsedSecs");
		DropColumn("dbo.NovaSetupGroups", "PatIdTypeCd");
		DropColumn("dbo.NovaSetupGroups", "LinLotValidation");
		DropColumn("dbo.NovaSetupGroups", "LinLotSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "LinLotScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "LinLotScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "LinLotNonBarcodeCmntReq");
		DropColumn("dbo.NovaSetupGroups", "LinLotListEnable");
		DropColumn("dbo.NovaSetupGroups", "LinLot2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "PhysIdMinLength");
		DropColumn("dbo.NovaSetupGroups", "PhysIdMaxLength");
		DropColumn("dbo.NovaSetupGroups", "PatIdMinLength");
		DropColumn("dbo.NovaSetupGroups", "PatIdMaxLength");
		DropColumn("dbo.NovaSetupGroups", "OpLoginMinLength");
		DropColumn("dbo.NovaSetupGroups", "OpLoginMaxLength");
		DropColumn("dbo.NovaSetupGroups", "DxIdMinLength");
		DropColumn("dbo.NovaSetupGroups", "DxIdMaxLength");
		DropColumn("dbo.NovaSetupGroups", "AccnIdMinLength");
		DropColumn("dbo.NovaSetupGroups", "AccnIdMaxLength");
		DropColumn("dbo.NovaSetupGroups", "DockLockSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "DockLockShiftTimes");
		DropColumn("dbo.NovaSetupGroups", "DockLockModeCd");
		DropColumn("dbo.NovaSetupGroups", "DockLockInterval");
		DropColumn("dbo.NovaSetupGroups", "DockLockElapsedHrs");
		DropColumn("dbo.NovaSetupGroups", "DockLockAlertMins");
		DropColumn("dbo.NovaSetupGroups", "ArchivedOvrwDisregardArchBit");
		DropColumn("dbo.NovaSetupGroups", "ArchivedObsRetainDays");
		DropColumn("dbo.NovaSetupGroups", "DxIdValidation");
		DropColumn("dbo.NovaSetupGroups", "DxIdSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "DxIdSmCbar");
		DropColumn("dbo.NovaSetupGroups", "DxIdSmC93");
		DropColumn("dbo.NovaSetupGroups", "DxIdSmC39");
		DropColumn("dbo.NovaSetupGroups", "DxIdSmC2o5");
		DropColumn("dbo.NovaSetupGroups", "DxIdSmC128");
		DropColumn("dbo.NovaSetupGroups", "DxIdSm2D");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejCbar");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC93");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC39");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC2o5");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanMaskFailRejC128");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanEnableCbar");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanEnableC93");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanEnableC39");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanEnableC2o5");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanEnableC128");
		DropColumn("dbo.NovaSetupGroups", "DxIdScanEnable2D");
		DropColumn("dbo.NovaSetupGroups", "DxIdPromptEnable");
		DropColumn("dbo.NovaSetupGroups", "DxIdNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "DxIdListEnable");
		DropColumn("dbo.NovaSetupGroups", "DxIdAlphaEnable");
		DropColumn("dbo.NovaSetupGroups", "DxId2dSEnableCd");
		DropColumn("dbo.NovaSetupGroups", "AccnIdValidation");
		DropColumn("dbo.NovaSetupGroups", "AccnIdSupOverrideEnable");
		DropColumn("dbo.NovaSetupGroups", "AccnIdSmCbar");
		DropColumn("dbo.NovaSetupGroups", "AccnIdSmC93");
		DropColumn("dbo.NovaSetupGroups", "AccnIdSmC39");
		DropColumn("dbo.NovaSetupGroups", "AccnIdSmC2o5");
		DropColumn("dbo.NovaSetupGroups", "AccnIdSmC128");
		DropColumn("dbo.NovaSetupGroups", "AccnIdSm2D");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanRequireAccept");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejCbar");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC93");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC39");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC2o5");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanMaskFailRejC128");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanEnableCd");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanEnableCbar");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC93");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC39");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC2o5");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanEnableC128");
		DropColumn("dbo.NovaSetupGroups", "AccnIdScanEnable2D");
		DropColumn("dbo.NovaSetupGroups", "AccnIdNonBarcodeCommentReq");
		DropColumn("dbo.NovaSetupGroups", "AccnIdListEnable");
		DropColumn("dbo.NovaSetupGroups", "AccnIdAlphaEnable");
		DropColumn("dbo.NovaSetupGroups", "AccnId2DsEnableCd");
		CreateIndex("dbo.NovaSetupGroups", "novaSetupId");
		AddForeignKey("dbo.NovaSetupGroups", "novaSetupId", "dbo.NovaSetups", "Id", cascadeDelete: true);
	}
}
