<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NovaProtocolService</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Autofac">
      <HintPath>..\NovaProtocolService\Autofac.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\NovaProtocolService\NLog.dll</HintPath>
    </Reference>
    <Reference Include="Yzkj.Novanet.Bussiness">
      <HintPath>..\NovaProtocolService\Yzkj.Novanet.Bussiness.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="Topshelf">
      <HintPath>..\NovaProtocolService\Topshelf.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceProcess" />
    <Reference Include="Yzkj.Novanet.Data">
      <HintPath>..\NovaProtocolService\Yzkj.Novanet.Data.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>