<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Yzkj.Novanet.Bussiness</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net452</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.AspNet.Identity.Owin">
      <HintPath>..\NovaProtocolService\Microsoft.AspNet.Identity.Owin.dll</HintPath>
    </Reference>
    <Reference Include="Yzkj.Novanet.Data">
      <HintPath>..\NovaProtocolService\Yzkj.Novanet.Data.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Owin">
      <HintPath>..\NovaProtocolService\Microsoft.Owin.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNet.Identity.Core">
      <HintPath>..\NovaProtocolService\Microsoft.AspNet.Identity.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Owin.Security">
      <HintPath>..\NovaProtocolService\Microsoft.Owin.Security.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Transactions" />
    <Reference Include="System.Xml" />
    <Reference Include="EntityFramework">
      <HintPath>..\NovaProtocolService\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="Microsoft.AspNet.Identity.EntityFramework">
      <HintPath>..\NovaProtocolService\Microsoft.AspNet.Identity.EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework.Extended">
      <HintPath>..\NovaProtocolService\EntityFramework.Extended.dll</HintPath>
    </Reference>
    <Reference Include="Yzkj.Novanet.Utility">
      <HintPath>..\NovaProtocolService\Yzkj.Novanet.Utility.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>