<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RTMLIS</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Configuration.Install" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="NNBaseLib">
      <HintPath>..\..\NovaNet v3.6.12.15 SP12\NovaNet 64\NNBaseLib.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>